[package]
name = "citimock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.12"
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
hyper = "0.14.25"
openssl = "0.10.49"
openssl-sys = "0.9.84"
serde = { version = "1.0.159", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tokio-openssl = "0.6.3"
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["map-request-body", "util"] }
